export const appcastFileName = 'appcast.xml'
export const bundleFileName = 'plugin.js'
export const manifestFileName = 'manifest.json'
export const packageJsonConfigKey = 'sketch-plugin-helper'
export const sourceDirectory = './src'
